"""a-team — main CLI entry point.

Subcommand layout:
    a-team                  picker (splash + arrow-key + filter)
    a-team <name>           direct-open shortcut for any agent name
    a-team all              restore every agent marked boot
    a-team new <name> [<path>]   path defaults to clipboard if omitted
    a-team here [name]      register current folder
    a-team scratch [label]  one-off chat in ~/.a-team/scratch/
    a-team rm <name>
    a-team ls
"""

import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import click
import questionary

from . import config, spawn, ui


def _clipboard_path() -> str | None:
    """Return clipboard contents if it looks like an existing directory.

    Designed for the Finder flow: Shift+Right-click → Copy "X" as Pathname,
    then `a-team new <name>` (no path arg) picks it up automatically.
    """
    try:
        result = subprocess.run(
            ["pbpaste"], capture_output=True, text=True, timeout=2, check=True
        )
    except (subprocess.SubprocessError, FileNotFoundError):
        return None
    candidate = result.stdout.strip()
    if not candidate:
        return None
    expanded = Path(candidate).expanduser()
    if expanded.is_dir():
        return str(expanded)
    return None


def _open(
    agent: dict,
    *,
    session_mode: str = "continue",
    topic: str | None = None,
    override_harness: str | None = None,
) -> bool:
    """Launch an agent under its saved harness (or a one-time override),
    resolving the harness-appropriate account config. One place so every launch
    path stays consistent. Returns False (after printing an actionable error) if
    the chosen harness isn't installed."""
    hk = config.resolve_harness(agent, override=override_harness).key
    host = config.resolve_host(agent)
    try:
        spawn.open_agent(
            agent["name"],
            agent["path"],
            session_mode=session_mode,
            topic=topic,
            harness=hk,
            host=host.key,
            session=agent.get("id"),
            config_dir=config.resolve_config_dir(agent, harness=hk),
        )
        return True
    except RuntimeError as e:
        ui.error(str(e))
        return False


class AteamGroup(click.Group):
    """Click Group that routes unknown command names to the direct-open
    shortcut handler. Lets `a-team EA` work without colliding with the
    real subcommands."""

    def get_command(self, ctx, cmd_name):
        rv = super().get_command(ctx, cmd_name)
        if rv is not None:
            return rv

        # Unknown name — treat as direct-open shortcut.
        @click.command(name=cmd_name, help=f"Open agent '{cmd_name}'.")
        @click.option(
            "--harness",
            "harness",
            type=click.Choice(["claude", "codex"]),
            default=None,
            help="Open under this harness once (default: the agent's saved harness). "
            "Does not change the saved default.",
        )
        def shortcut(harness: str | None):
            agent = config.find_agent(cmd_name)
            if not agent:
                ui.error(f"agent not found: {cmd_name}")
                ui.console.print(
                    "[soft]Run `a-team ls` to see registered agents.[/soft]"
                )
                sys.exit(1)
            if not _open(agent, override_harness=harness):
                sys.exit(1)

        return shortcut


@click.group(
    cls=AteamGroup,
    invoke_without_command=True,
    context_settings={"help_option_names": ["-h", "--help"]},
)
@click.option("--no-splash", is_flag=True, help="Suppress the splash banner.")
@click.pass_context
def cli(ctx: click.Context, no_splash: bool) -> None:
    """Parallel Claude Code session manager. I love it when a plan comes together."""
    ctx.ensure_object(dict)
    ctx.obj["no_splash"] = no_splash

    if ctx.invoked_subcommand is None:
        run_picker(no_splash=no_splash)


@cli.command("sync")
@click.option("--dry-run", is_flag=True, help="Show what would be written, change nothing.")
def sync_cmd(dry_run: bool) -> None:
    """Write each host's boot list from the registry.

    The registry is the source of truth. A host that cannot run a-team (no
    Python package installed there) still needs to restore its own sessions
    after a reboot, so it gets a generated list it can read locally. Six files
    once described an agent and drifted within a day; this keeps it to one.
    """
    from . import config as _config
    from . import hosts as _hosts

    by_host: dict[str, list[dict]] = {}
    for a in _config.boot_agents():
        by_host.setdefault(_hosts.normalize_key(a.get("host")) or "local", []).append(a)

    if not by_host:
        click.echo("  no agents marked boot = true")
        return

    for host, agents in sorted(by_host.items()):
        lines = [
            "# GENERATED by `a-team sync` from the a-team registry. Do not edit.",
            "# Edit the registry instead, then run sync again.",
            "# tmux-name\tfolder\tremote-control-name\tmcp-config\tsettings-file",
            "# (- for none). BOTH config columns matter: the mcp file fences the",
            "# session to its tenant, the settings file denies other customers'",
            "# paths and installs the Bash guard. Neither is sufficient alone.",
        ]
        for a in sorted(agents, key=lambda x: x["name"]):
            lines.append("\t".join([
                a["session"], a["path"], a["rc"],
                a.get("mcp") or "-", a.get("settings") or "-",
            ]))
        body = "\n".join(lines) + "\n"

        target = "~/.config/session-boot/sessions.tsv"
        if dry_run:
            click.echo(f"  {host}: would write {len(agents)} agents to {target}")
            for a in sorted(agents, key=lambda x: x["name"]):
                click.echo(f"      {a['session']:<26} {a['path']}")
            continue

        if host == "local":
            path = Path.home() / ".config" / "session-boot" / "sessions.tsv"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)
        else:
            # Written over stdin, never as a command argument: agent names are
            # user data and must not be spliced into a shell command line.
            proc = subprocess.run(
                ["ssh", host, "mkdir -p ~/.config/session-boot && cat > ~/.config/session-boot/sessions.tsv"],
                input=body, text=True, capture_output=True,
            )
            if proc.returncode != 0:
                click.echo(f"  {host}: FAILED to write ({proc.stderr.strip()[:120]})", err=True)
                continue
        click.echo(f"  {host}: wrote {len(agents)} agents to {target}")


@cli.command("all")
@click.pass_context
def all_cmd(ctx: click.Context) -> None:
    """Restore the agents marked boot (post-reboot)."""
    no_splash = ctx.obj.get("no_splash", False)
    # Archived agents are never restored, and booting is opt in: most of the
    # registry is dormant history, not things that should come back.
    boot = config.boot_agents()

    if not boot:
        ui.warn("No agents are marked boot = true. Set boot on the ones that should come back.")
        return

    if not no_splash:
        ui.print_splash(len(agents))

    ui.info(f"Restoring {len(boot)} agents…")
    spawn.open_all(boot)
    ui.info("Done.")


def _record(agent: dict) -> dict:
    """The full normalized record for an agent, as JSON-safe data.

    Agents are the main consumers of this output, so it emits every field
    rather than a hand-picked subset: a caller that has to shell out twice
    because the first call omitted `account` is a caller that will instead
    go parse agents.toml, which is what `resolve` exists to prevent.
    `ssh` is derived, not stored, and is what you actually need to reach it.
    """
    out = dict(agent)
    out["ssh"] = config.resolve_host(agent).ssh_alias
    out["status"] = agent.get("status") or "active"
    out["boot"] = bool(agent.get("boot"))
    return out


@cli.command("resolve")
@click.argument("identifier")
@click.option("--json", "as_json", is_flag=True, help="Emit the full record as JSON.")
@click.option("--field", type=click.Choice(["id", "name", "path", "harness", "host"]), default=None,
              help="Print just one field (for shell scripts).")
def resolve_cmd(identifier: str, as_json: bool, field: str | None) -> None:
    """Resolve an agent identifier (id, exact name, or alias) to its record.

    The single canonical resolver for shell helpers: instead of each script
    re-parsing agents.toml, they call this. Resolves by stable id → exact name →
    alias, refuses ambiguous matches (exit 2), and exits 1 if not found. Default
    output is the stable id; --field or --json for more.
    """
    try:
        agent = config.resolve_agent(identifier)
    except ValueError as e:  # ambiguous identifier
        ui.error(str(e))
        sys.exit(2)
    if not agent:
        ui.error(f"no agent matches {identifier!r}")
        sys.exit(1)
    if as_json:
        click.echo(json.dumps(_record(agent)))
    elif field:
        click.echo(agent[field])
    else:
        click.echo(agent["id"])


@cli.command("migrate")
@click.option("--apply", "do_apply", is_flag=True, help="Write the changes (default is a dry run).")
def migrate_cmd(do_apply: bool) -> None:
    """Backfill stable ids + harness into agents.toml (rename-safe identity).

    Dry run by default: shows exactly what would change and writes nothing.
    Pass --apply to write; the current registry is backed up to
    <name>.bak-<timestamp> first, and all other fields/tables are preserved.
    """
    report = config.migrate_registry(apply=do_apply)
    changes = report["changes"]
    if not changes:
        ui.info(f"Registry already migrated ({report['total']} agents). Nothing to do.")
        return
    verb = "Migrated" if do_apply else "Would migrate"
    ui.info(f"{verb} {len(changes)} of {report['total']} agents in {report['path']}:")
    for name, agent_id, harness in changes:
        ui.console.print(f"  [soft]{name}[/soft] → id=[bold]{agent_id}[/bold], harness={harness}")
    if do_apply:
        ui.info(f"Backup written to {report['backup']}")
        ui.info("Done. Rollback: restore the .bak file over agents.toml.")
    else:
        ui.warn("Dry run — nothing written. Re-run with --apply to write.")


@cli.command("here")
@click.argument("name", required=False, default=None)
@click.option("--category", "-c", default=None, help="Category for grouping in the picker.")
@click.option("--account", default=None, help="Claude account override (e.g. 'work'). Omit to use the category's default.")
@click.option("--harness", type=click.Choice(["claude", "codex"]), default=None, help="Harness to run this agent under (default: claude).")
@click.option("--host", default=None, help="Where the agent lives: 'local' or a host from the [hosts] table (default: local).")
def here_cmd(name: str | None, category: str | None, account: str | None, harness: str | None, host: str | None) -> None:
    """Register the current working directory as an agent.

    Name defaults to the directory's basename if omitted. Useful for adding
    an existing project folder you're already working in without typing the
    full path.

    Examples:
        cd ~/Documents/some-project && a-team here
        cd ~/Documents/some-project && a-team here MyAgent -c Work
    """
    try:
        cwd = os.getcwd()
    except OSError as e:
        ui.error(f"Can't read current directory ({e}). Try `cd ~` first.")
        sys.exit(1)
    if name is None:
        name = Path(cwd).name
    try:
        agent = config.add_agent(name, cwd, category=category, account=account, harness=harness, host=host)
    except ValueError as e:
        ui.error(str(e))
        sys.exit(1)
    cat_suffix = f", {agent['category']}" if agent.get("category") else ""
    ui.info(f"Added agent '{agent['name']}' ({agent['harness']}, host={agent['host']}{cat_suffix}) → {agent['path']}")


def _slugify(label: str) -> str:
    """Lowercase, replace runs of non-alphanumerics with single hyphens,
    trim leading/trailing hyphens. Empty string in → empty string out."""
    return config.slugify(label)


def _scratch_name() -> str:
    """Build a default scratch session name from the current timestamp."""
    return time.strftime("%Y-%m-%d_%H-%M")


def _create_scratch(label: str | None) -> dict | None:
    """Create a scratch session: timestamped folder under SCRATCH_DIR,
    registered under category=Scratch. Returns the agent
    dict, or None on failure (with an error already printed)."""
    config.SCRATCH_DIR.mkdir(parents=True, exist_ok=True)

    base = _scratch_name()
    slug = _slugify(label or "")
    name = f"{base}_{slug}" if slug else base

    # Resolve name conflicts by appending a counter.
    suffix = 1
    candidate = name
    while config.find_agent(candidate) is not None:
        suffix += 1
        candidate = f"{name}-{suffix}"
    name = candidate

    folder = config.SCRATCH_DIR / name
    try:
        folder.mkdir(parents=False, exist_ok=False)
    except OSError as e:
        ui.error(f"could not create scratch folder {folder}: {e}")
        return None

    try:
        agent = config.add_agent(
            name, str(folder), category=config.SCRATCH_CATEGORY,
        )
    except ValueError as e:
        ui.error(str(e))
        return None
    return agent


@cli.command("scratch")
@click.argument("label", required=False, default=None)
def scratch_cmd(label: str | None) -> None:
    """Create a one-off scratch session and open it immediately.

    Scratch sessions live under ~/.a-team/scratch/<timestamp>[_<label>]/,
    are registered under `category=Scratch`, and are not booted by
    `a-team all`. They appear in the picker under a 'Scratch' section
    capped at the 10 most recent (with 'Show all scratch' to expand).
    """
    agent = _create_scratch(label)
    if agent is None:
        sys.exit(1)
    ui.info(f"Created scratch '{agent['name']}' → {agent['path']}")
    _open(agent)


@cli.command("new")
@click.argument("name")
@click.argument("path", required=False, default=None)
@click.option("--category", "-c", default=None, help="Category for grouping in the picker.")
@click.option("--account", default=None, help="Claude account override (e.g. 'work'). Omit to use the category's default.")
@click.option("--harness", type=click.Choice(["claude", "codex"]), default=None, help="Harness to run this agent under (default: claude).")
@click.option("--host", default=None, help="Where the agent lives: 'local' or a host from the [hosts] table. The folder is created on that machine.")
@click.option("--sibling", "sibling_of", default=None, metavar="PARENT",
              help="Clone PARENT's host, category, account, harness and MCP grant; record the lineage.")
@click.option("--boot/--no-boot", "boot", default=None,
              help="Start this agent on reboot (`a-team all`). Default: no.")
def new_cmd(name: str, path: str | None, category: str | None, account: str | None,
            harness: str | None, host: str | None, sibling_of: str | None,
            boot: bool | None) -> None:
    """Register a new agent.

    PATH lookup order if omitted:
      1. macOS clipboard (Finder: Shift+Right-click → Copy as Pathname)
      2. Scaffold <default_parent>/<name>/ if `default_parent` is set
         (see `a-team config default-parent <path>`)

    With --sibling, the new agent inherits the parent's host, category,
    account, harness and MCP grant unless you override them explicitly, and
    records `parent` so the lineage is visible in the registry rather than
    only in whoever's memory created it.
    """
    from . import hosts as _hosts

    parent = None
    if sibling_of:
        try:
            parent = config.resolve_agent(sibling_of)
        except ValueError as e:  # ambiguous
            ui.error(str(e))
            sys.exit(2)
        if not parent:
            ui.error(f"no agent matches {sibling_of!r} to be a sibling of")
            sys.exit(1)
        # Explicit flags win; the parent only fills the gaps.
        host = host if host is not None else parent.get("host")
        category = category if category is not None else parent.get("category")
        account = account if account is not None else parent.get("account")
        harness = harness if harness is not None else parent.get("harness")

    # No --host given? Use the configured default (a-team config default-host).
    host_key = _hosts.normalize_key(host if host is not None else config.get_default_host())
    if host_key == _hosts.DEFAULT_HOST:
        resolved = _resolve_new_path(name, path)
        if resolved is None:
            sys.exit(1)
    else:
        # Remote host: do NOT resolve or scaffold against this filesystem.
        # Pass the raw path through; `~` is expanded on the REMOTE machine.
        # With no path given, mirror the local convention: ~/agents/<slug>.
        resolved = path or f"~/agents/{config.slugify(name)}"

    try:
        agent = config.add_agent(name, resolved, category=category, account=account, harness=harness, host=host_key, create_dir=True)
    except ValueError as e:
        ui.error(str(e))
        sys.exit(1)

    extra: dict = {}
    if parent:
        extra["parent"] = parent["id"]
        # The grant is the whole point of a sibling: a second session for the
        # same client must see that tenant and no other, and must be fenced off
        # other customers' folders. Derive BOTH halves from the account rather
        # than copying whichever the parent happened to have recorded.
        mcp, settings = config.grant_paths(agent.get("account"))
        if mcp:
            extra["mcp"] = mcp
            extra["settings"] = settings
    if boot:
        extra["boot"] = True
    if extra:
        agent = config.set_fields(agent["name"], **extra)
    cat_suffix = f", {agent['category']}" if agent.get("category") else ""
    ui.info(f"Added agent '{agent['name']}' ({agent['harness']}, host={agent['host']}{cat_suffix}) → {agent['path']}")
    if parent:
        ui.info(f"  sibling of '{parent['name']}'"
                + (f", sharing its MCP grant ({agent['mcp']})" if agent.get("mcp") else ""))
        ui.info("  Give it its own --label when you open it, or it cannot be addressed by name.")


def _resolve_new_path(name: str, path: str | None) -> str | None:
    """Decide the path for a new agent, given (possibly None) input.

    Behavior:
      - If `path` exists: register it as-is.
      - If `path` doesn't exist but its parent does: scaffold the folder
        and register it.
      - If `path` is missing entirely: try clipboard, then default_parent.
    Returns the resolved path string, or None if it couldn't be determined
    (in which case an error has already been printed).
    """
    if path:
        p = Path(path).expanduser()
        if p.is_dir():
            return str(p)
        if p.parent.is_dir():
            try:
                p.mkdir(parents=False, exist_ok=False)
            except OSError as e:
                ui.error(f"could not create {p}: {e}")
                return None
            ui.info(f"Created folder: {p}")
            return str(p)
        ui.error(f"path does not exist and parent is missing: {path}")
        return None

    clip = _clipboard_path()
    if clip:
        ui.info(f"Using path from clipboard: {clip}")
        return clip

    parent = config.get_default_parent()
    if parent:
        scaffolded = parent / config.slugify(name)
        try:
            scaffolded.mkdir(parents=False, exist_ok=False)
        except FileExistsError:
            if not scaffolded.is_dir():
                ui.error(f"{scaffolded} exists but is not a directory")
                return None
            ui.info(f"Using existing folder: {scaffolded}")
        else:
            ui.info(f"Created folder: {scaffolded}")
        return str(scaffolded)

    ui.error("No path argument, no valid clipboard path, and no default_parent set.")
    ui.console.print(
        "[soft]Set one with: a-team config default-parent ~/agents[/soft]"
    )
    return None


@cli.command("tui")
def tui_cmd() -> None:
    """Open the live dashboard (requires the 'tui' extra)."""
    try:
        from . import tui
    except ImportError:
        ui.error("the dashboard needs textual: pip install 'a-team[tui]'")
        raise SystemExit(1)
    tui.run()


@cli.group("config")
def config_cmd() -> None:
    """Show or set a-team settings (stored in agents.toml)."""


@config_cmd.command("show")
def config_show() -> None:
    """Print all current settings."""
    settings = config.load_settings()
    if not settings:
        ui.console.print("[soft]No settings set.[/soft]")
        return
    for k, v in settings.items():
        print(f"{k}\t{v}")


@config_cmd.command("default-parent")
@click.argument("path", required=False, default=None)
@click.option("--unset", is_flag=True, help="Clear the default_parent setting.")
def config_default_parent(path: str | None, unset: bool) -> None:
    """Set the default parent directory for new agents.

    When `a-team new <name>` is called without a path and the clipboard
    has no valid path, a folder is created under <default_parent>/<name>/.
    """
    if unset:
        config.set_setting("default_parent", None)
        ui.info("Cleared default_parent.")
        return
    if not path:
        current = config.get_setting("default_parent")
        if current:
            print(current)
        else:
            ui.console.print("[soft]default_parent is not set.[/soft]")
        return

    expanded = Path(path).expanduser().resolve()
    if not expanded.is_dir():
        ui.error(f"path is not a directory: {expanded}")
        sys.exit(1)
    config.set_setting("default_parent", str(expanded))
    ui.info(f"Set default_parent → {expanded}")


@config_cmd.command("default-host")
@click.argument("host_key", required=False, default=None)
@click.option("--unset", is_flag=True, help="Clear the default_host setting (back to local).")
def config_default_host(host_key: str | None, unset: bool) -> None:
    """Set where `a-team new` puts agents when --host isn't given.

    Use a key from the [hosts] table, or 'local' for this machine.
    """
    from . import hosts as _hosts

    if unset:
        config.set_setting("default_host", None)
        ui.info("Cleared default_host (new agents default to local).")
        return
    if not host_key:
        print(config.get_default_host())
        return
    try:
        key = _hosts.normalize_key(host_key)
    except ValueError as e:
        ui.error(str(e))
        sys.exit(1)
    config.set_setting("default_host", key)
    ui.info(f"Set default_host → {key}")


@cli.command("rm")
@click.argument("name")
def rm_cmd(name: str) -> None:
    """Unregister an agent. Does NOT delete the folder."""
    if config.remove_agent(name):
        ui.info(f"Removed agent '{name}' (folder kept).")
    else:
        ui.error(f"agent not found: {name}")
        sys.exit(1)


@cli.command("open")
@click.argument("name")
@click.option("--new", "force_new", is_flag=True,
              help="Start a fresh session instead of attaching to the running one.")
@click.option("--label", default=None,
              help="Name this parallel session. Required to address it by name later.")
@click.option("--list", "list_only", is_flag=True, help="List live sessions on the agent's host.")
def open_cmd(name: str, force_new: bool, label: str | None, list_only: bool) -> None:
    """Open a window on an agent: attach if it is running, else start it.

    Attaching is the default because an agent on the server is already alive
    with its context; starting a second one beside it splits the work in two
    and neither half knows about the other.
    """
    try:
        agent = config.resolve_agent(name)
    except ValueError as e:
        ui.error(str(e))
        sys.exit(2)
    if not agent:
        ui.error(f"no agent matches {name!r}")
        sys.exit(1)

    host = agent.get("host") or "local"
    sessions = spawn.tmux_sessions(host)

    if list_only:
        if sessions is None:
            ui.error(f"could not reach {host}")
            sys.exit(1)
        for sname in sessions:
            click.echo(f"  {sname}")
        return

    if sessions is None:
        # Unreachable is not idle. Starting a "fresh" session here would at
        # best fail and at worst duplicate one that is already running.
        ui.error(f"could not reach {host}; not starting anything. "
                 f"Check `ssh {config.resolve_host(agent).ssh_alias}` and Tailscale.")
        sys.exit(1)

    want = agent.get("session") or agent["id"]
    if want in sessions and not force_new:
        spawn.attach_window(want, host)
        ui.info(f"Attached a window to '{want}' on {host}.")
        return

    if force_new and not label:
        ui.warn("A parallel session with no --label cannot be addressed by name. "
                "Two unlabelled ones make both unreachable unambiguously.")
    try:
        spawn.open_agent(
            agent["name"], agent["path"],
            topic=label,
            harness=agent.get("harness", "claude"),
            host=host,
            session=label or agent["id"],
            config_dir=config.resolve_config_dir(agent),
        )
    except RuntimeError as e:
        ui.error(str(e))
        sys.exit(1)
    ui.info(f"Started '{agent['name']}'" + (f" (label: {label})" if label else "") + f" on {host}.")


@cli.command("grants")
@click.option("--json", "as_json", is_flag=True, help="Emit the audit as JSON.")
@click.option("--fix", is_flag=True, help="Backfill missing mcp/settings paths from each agent's account.")
@click.option("--check-files", is_flag=True, help="Also verify the config files exist on each agent's host (one SSH per host).")
def grants_cmd(as_json: bool, fix: bool, check_files: bool) -> None:
    """Audit need-to-know wiring: which agents are fenced, and how completely.

    Need-to-know has two halves (an --only-mcp file and a --settings file with
    the Bash guard) and neither works alone. This reports agents wired to only
    one, which look correct in the registry and are not. --check-files goes
    further and asks each host whether the files are actually there, because a
    recorded path to a file that was never generated fences nothing.
    """
    rows = []
    for a in config.active_agents():
        acct = a.get("account")
        want_mcp, want_settings = config.grant_paths(acct)
        rows.append({
            "name": a["name"],
            "host": a.get("host"),
            "account": acct,
            "mcp": a.get("mcp"),
            "settings": a.get("settings"),
            "expected_mcp": want_mcp,
            "expected_settings": want_settings,
        })

    if check_files:
        _check_grant_files(rows)

    for r in rows:
        if not r["account"]:
            r["state"] = "ungranted"          # no account: not fenced, by design
        elif r["mcp"] and r["settings"]:
            r["state"] = "full"
        elif r["mcp"] or r["settings"]:
            r["state"] = "HALF"               # the dangerous one
        else:
            r["state"] = "MISSING"
        if check_files and r["state"] in ("full", "HALF"):
            if r.get("files_present") is False:
                r["state"] = "NO FILES"
            elif r.get("empty_tenant"):
                # Fenced, but to nothing: no Atlas tenant of its own yet.
                r["state"] = "NO TENANT"

    if fix:
        fixed = 0
        for r in rows:
            if r["account"] and (r["mcp"] != r["expected_mcp"] or r["settings"] != r["expected_settings"]):
                config.set_fields(r["name"], mcp=r["expected_mcp"], settings=r["expected_settings"])
                ui.info(f"  {r['name']}: wired both halves for account '{r['account']}'")
                fixed += 1
        ui.info(f"Backfilled {fixed} agent(s)." if fixed else "Nothing to backfill.")
        return

    if as_json:
        click.echo(json.dumps(rows, indent=2))
        return

    width = max((len(r["name"]) for r in rows), default=4)
    for r in rows:
        acct = r["account"] or "-"
        click.echo(f"{r['name']:<{width}}  {r['state']:<9}  account={acct}")
    bad = [r for r in rows if r["state"] in ("HALF", "MISSING", "NO FILES")]
    if bad:
        ui.warn(f"{len(bad)} agent(s) with an account are not fully fenced: "
                + ", ".join(r["name"] for r in bad))
        ui.warn("Run `a-team grants --fix`, then `agent-grants` on that host to generate the files.")


EMPTY_MCP = '"mcpServers": {}'


def _check_grant_files(rows: list[dict]) -> None:
    """Ask each host, once, which of the referenced grant files exist."""
    from . import hosts as _hosts

    by_host: dict[str, list[dict]] = {}
    for r in rows:
        if r["mcp"] or r["settings"]:
            by_host.setdefault(_hosts.normalize_key(r["host"]), []).append(r)

    for host, hrows in by_host.items():
        paths = sorted({p for r in hrows for p in (r["mcp"], r["settings"]) if p})
        # One shell, one round trip. The test must expand ~ but the echo must
        # NOT: `echo ~/x` prints the expanded path, which never equals the
        # recorded string, so every file reads as absent. Echo an index and
        # map it back here instead of matching on the path text.
        # For an MCP config, existing is not the same as granting anything:
        # a file declaring an empty mcpServers fences the session to no tenant
        # at all. That is a real state, but not the one "wired" implies, so
        # report it separately rather than as a pass.
        checks = []
        for i, path in enumerate(paths):
            if "grants/mcp" in path:
                checks.append(
                    "[ -f {p} ] && {{ grep -q '{empty}' {p} "
                    "&& echo '{i}:empty' || echo '{i}:ok'; }}".format(
                        p=path, i=i, empty=EMPTY_MCP)
                )
            else:
                checks.append("[ -f {p} ] && echo '{i}:ok'".format(p=path, i=i))
        script = "; ".join(checks)
        try:
            if host == _hosts.DEFAULT_HOST:
                out = subprocess.run(["sh", "-c", script], capture_output=True,
                                     text=True, timeout=20).stdout
            else:
                alias = _hosts.all_hosts()[host].ssh_alias
                out = subprocess.run(["ssh", "-o", "ConnectTimeout=8", alias, script],
                                     capture_output=True, text=True, timeout=25).stdout
        except (subprocess.SubprocessError, KeyError, OSError) as e:
            # Unreachable is not the same as absent. Say so rather than
            # reporting every agent on that host as unfenced.
            ui.warn(f"could not check files on {host}: {e}")
            for r in hrows:
                r["files_present"] = None
            continue
        found, empty = set(), set()
        for token in out.split():
            idx, _, state = token.partition(":")
            if not idx.isdigit():
                continue
            found.add(paths[int(idx)])
            if state == "empty":
                empty.add(paths[int(idx)])
        for r in hrows:
            want = [p for p in (r["mcp"], r["settings"]) if p]
            r["files_present"] = all(p in found for p in want)
            r["missing_files"] = [p for p in want if p not in found]
            r["empty_tenant"] = bool(r["mcp"]) and r["mcp"] in empty


@cli.command("archive")
@click.argument("names", nargs=-1, required=True)
def archive_cmd(names: tuple[str, ...]) -> None:
    """Archive one or more agents: out of the picker, kept in the registry.

    Archiving clears `boot`, so an archived agent cannot come back on the next
    reboot. The folder is untouched, and the id is kept, so `unarchive` puts
    the agent back exactly as it was.
    """
    failed = False
    for name in names:
        try:
            a = config.set_status(name, "archived")
        except ValueError as e:
            ui.error(str(e))
            failed = True
            continue
        ui.info(f"Archived '{a['name']}' (folder kept, boot cleared).")
    if failed:
        sys.exit(1)


@cli.command("unarchive")
@click.argument("names", nargs=-1, required=True)
def unarchive_cmd(names: tuple[str, ...]) -> None:
    """Put archived agents back in the picker.

    `boot` is NOT restored: decide again whether it should start on reboot.
    """
    failed = False
    for name in names:
        try:
            a = config.set_status(name, "active")
        except ValueError as e:
            ui.error(str(e))
            failed = True
            continue
        ui.info(f"Reactivated '{a['name']}'. Set boot separately if it should start on reboot.")
    if failed:
        sys.exit(1)


@cli.command("help")
def help_cmd() -> None:
    """Show the styled help panel (same as the picker's `? Help` entry)."""
    ui.show_help(interactive=False)


@cli.command("ls")
@click.option("--all", "show_all", is_flag=True, help="Include archived agents.")
@click.option("--json", "as_json", is_flag=True, help="Emit full records as a JSON array.")
@click.option("--boot", "boot_only", is_flag=True, help="Only agents marked boot.")
@click.option("--host", default=None, help="Only agents on this host.")
def ls_cmd(show_all: bool, as_json: bool, boot_only: bool, host: str | None) -> None:
    """List registered agents in plain text (pipe-friendly).

    Output: name <TAB> category <TAB> path, or full records with --json.
    """
    from . import hosts as _hosts

    agents = config.load_agents_normalized() if show_all else config.active_agents()
    if boot_only:
        agents = [a for a in agents if a.get("boot")]
    if host:
        want = _hosts.normalize_key(host)
        agents = [a for a in agents if _hosts.normalize_key(a.get("host")) == want]
    if as_json:
        # An empty result is still valid JSON, so a caller can parse
        # unconditionally instead of special-casing no output.
        click.echo(json.dumps([_record(a) for a in agents], indent=2))
        return
    if not agents:
        return
    name_width = max(len(a["name"]) for a in agents)
    cat_width = max((len(a.get("category", "")) for a in agents), default=0)
    for a in agents:
        cat = a.get("category", "")
        print(f"{a['name']:<{name_width}}\t{cat:<{cat_width}}\t{a['path']}")


# ---------------------------------------------------------------------------
# Picker mode (default when no subcommand given)
# ---------------------------------------------------------------------------


def run_picker(no_splash: bool = False) -> None:
    """Show the splash + main picker; loop until the user cancels.

    Acts as a home menu: every sub-flow (create / manage / open) returns
    here, so the user can pick multiple agents in one session.
    """
    splash_shown = False
    last_action: str | None = None
    expand_scratch = False  # toggled by ACTION_SHOW_ALL_SCRATCH

    while True:
        # The picker shows working agents only. Archived ones stay in the
        # registry (and in `a-team ls --all`) but are not choices here.
        agents = config.active_agents()
        # macOS can return EPERM from getcwd() when the cwd's parent permissions
        # change mid-session, the dir is renamed, or iCloud evicts it. Fall back
        # to home rather than crash the picker loop.
        try:
            cwd = os.getcwd()
        except OSError:
            cwd = str(Path.home())
        is_home = cwd == str(Path.home())
        cwd_unregistered = (
            bool(agents) and not config.is_path_registered(cwd) and not is_home
        )

        if not no_splash and not splash_shown:
            ui.print_splash(len(agents))
            splash_shown = True

        if last_action:
            ui.console.print(f"  [accent]✓[/accent] [nav]{last_action}[/nav]\n")
            last_action = None

        if not agents:
            ui.info("No agents yet. Let's create your first one.")
            msg = _create_agent_flow(default_path=cwd)
            if not config.active_agents():
                return
            ui.console.clear()
            splash_shown = False
            last_action = msg
            continue

        selection = ui.pick_agent(
            agents,
            cwd_unregistered=cwd_unregistered,
            expand_scratch=expand_scratch,
        )

        if selection is None or selection == ui.ACTION_CANCEL:
            return

        if selection == ui.ACTION_CREATE:
            msg = _create_agent_flow()
            ui.console.clear()
            splash_shown = False
            last_action = msg
            continue

        if selection == ui.ACTION_REGISTER_CWD:
            msg = _create_agent_flow(default_path=cwd)
            ui.console.clear()
            splash_shown = False
            last_action = msg
            continue

        if selection == ui.ACTION_NEW_SCRATCH:
            msg = _scratch_via_picker()
            ui.console.clear()
            splash_shown = False
            last_action = msg
            continue

        if selection == ui.ACTION_SHOW_ALL_SCRATCH:
            # Flip the flag and re-render. No screen clear so the user
            # stays oriented at the same scroll position.
            expand_scratch = True
            continue

        if selection == ui.ACTION_MANAGE:
            msg = _manage_flow(agents)
            ui.console.clear()
            splash_shown = False
            last_action = msg
            continue

        if selection == ui.ACTION_HELP:
            ui.show_help()
            splash_shown = False  # screen was cleared; re-show splash
            continue

        # User picked an actual agent — ask resume vs fresh chat (with the
        # harness shown), then open. Chosen harness starts at the saved default;
        # "Switch harness…" re-asks under the other one for this open only and
        # never changes the saved default.
        chosen_harness = config.resolve_harness(selection).key
        mode = ui.prompt_chat_mode(
            selection["name"], harness_label=config.resolve_harness(selection, override=chosen_harness).label
        )
        while mode == ui.CHAT_MODE_SWITCH_HARNESS:
            picked = ui.prompt_harness(selection["name"], chosen_harness)
            if picked:
                chosen_harness = picked
            mode = ui.prompt_chat_mode(
                selection["name"],
                harness_label=config.resolve_harness(selection, override=chosen_harness).label,
            )
        if mode is None or mode == ui.CHAT_MODE_CANCEL:
            # Cancelled the sub-prompt; loop back to the picker without opening.
            continue
        topic: str | None = None
        if mode == ui.CHAT_MODE_NEW:
            topic_input = ui.prompt_chat_topic()
            if topic_input is None:
                continue  # cancelled
            topic = topic_input.strip() or None
        session_mode = {
            ui.CHAT_MODE_NEW: "new",
            ui.CHAT_MODE_CONTINUE: "continue",
            ui.CHAT_MODE_RESUME: "resume",
        }.get(mode, "continue")
        _open(selection, session_mode=session_mode, topic=topic, override_harness=chosen_harness)
        label = f"{selection['name']}: {topic}" if topic else selection["name"]
        suffix = {"new": " (new chat)", "resume": " (resume)"}.get(session_mode, "")
        last_action = f"Opened {label}{suffix}"
        # Collapse scratch back to last-10 on next render.
        expand_scratch = False


def _scratch_via_picker() -> str | None:
    label = ui.prompt_scratch_label()
    if label is None:
        return None  # user cancelled at the prompt
    label = label.strip()
    agent = _create_scratch(label or None)
    if agent is None:
        return None
    _open(agent)
    return f"Opened scratch '{agent['name']}'"


def _create_agent_flow(default_path: str | None = None) -> str | None:
    parent = config.get_default_parent()
    new = ui.prompt_new_agent(
        default_path=default_path,
        existing_categories=config.list_categories(),
        default_parent=str(parent) if parent else None,
    )
    if not new:
        return None

    # A bare/relative folder must not resolve against the cwd: a-team is often
    # launched from an arbitrary session folder (e.g. a Google Drive dir), which
    # silently scaffolded agents in the wrong place. Anchor relatives to
    # default_parent when one is set.
    p = Path(new["path"]).expanduser()
    if not p.is_absolute():
        p = (parent / p) if parent else p.resolve()

    # Scaffold the folder if it doesn't exist but the parent does.
    if not p.exists():
        if p.parent.is_dir():
            try:
                p.mkdir(parents=False, exist_ok=False)
            except OSError as e:
                ui.error(f"could not create {p}: {e}")
                return None
        else:
            ui.error(f"path does not exist and parent is missing: {p}")
            return None

    try:
        agent = config.add_agent(
            new["name"],
            str(p),
            category=new.get("category"),
            account=new.get("account"),
            harness=new.get("harness"),
            host=new.get("host"),
            create_dir=True,
        )
    except ValueError as e:
        ui.error(str(e))
        return None

    cat = f" ({agent['category']})" if agent.get("category") else ""
    return f"Added '{agent['name']}'{cat}"

    # Offer to open it right away.
    open_now = questionary.confirm(
        f"Open '{agent['name']}' now?",
        default=True,
        style=questionary.Style([("question", "bold"), ("pointer", "fg:#ff8800")]),
    ).ask()
    if open_now:
        _open(agent)


def _manage_flow(agents: list[dict]) -> str | None:
    target = ui.pick_agent_for_management(agents)
    if not target or not isinstance(target, dict):
        return None

    result = ui.prompt_manage_agent(
        target, existing_categories=config.list_categories()
    )
    if not result:
        return None

    try:
        if result["action"] == "rename":
            config.update_agent(target["name"], new_name=result["new_name"])
            return f"Renamed '{target['name']}' to '{result['new_name']}'"
        if result["action"] == "edit_path":
            config.update_agent(target["name"], new_path=result["new_path"])
            return f"Updated path for '{target['name']}'"
        if result["action"] == "edit_category":
            config.update_agent(target["name"], new_category=result["new_category"])
            label = result["new_category"] or "(none)"
            return f"Set category of '{target['name']}' to {label}"
        if result["action"] == "remove":
            config.remove_agent(target["name"])
            return f"Removed '{target['name']}' (folder kept)"
    except ValueError as e:
        ui.error(str(e))
        return None
    return None


def main() -> None:
    """Entry point declared in pyproject.toml."""
    cli()


if __name__ == "__main__":
    main()
